### ISSUE TITLE
Unable to import custom react-three-fiber element even after declaring custom type in react-three-fiber module

### ISSUE THREAD

**Issue by jdbbdj** [sjoerdvanBommel/youtube#2]
the error still persist by following your steps:
1.Create a FloorComponent
2.Create a FloorMaterial.ts with simple extension of ShaderMaterial
3.declare the FloorMaterial as floorMaterial by extends of @react-three-fiber
4.import the "./three-elements.ts" to main.tsx

by declaring the <floorMaterial/> on the current file it still has an error of JSX.IntrinsicElements can you help me with this?

there is similar stackoverflow issue regarding this https://stackoverflow.com/questions/75752539/unable-to-import-custom-react-three-fiber-element-even-after-declaring-custom-ty/75862133#75862133

**Comment by sjoerdvanBommel** [comment]
Hey @jdbbdj, I'm sorry for taking so long, are you still running into this issue?

**Comment by sjoerdvanBommel** [comment]
Closing this, feel free to re-open if the issue still occurs.
